// <auto-generated />
using System;
using AgroMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroMonitor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroMonitorContext))]
    [Migration("20260608142313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroMonitor.Domain.Entities.Slot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("PLANTED_AT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("POSITION");

                    b.Property<long>("SpeciesId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("TB_CAD_SLOT", (string)null);
                });

            modelBuilder.Entity("AgroMonitor.Domain.Entities.Species", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("COMMON_NAME");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal?>("FrostMinTemp")
                        .HasPrecision(4, 1)
                        .HasColumnType("DECIMAL(4,1)")
                        .HasColumnName("FROST_MIN_TEMP");

                    b.Property<decimal>("MaxHumidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("MAX_HUMIDITY");

                    b.Property<decimal>("MinHumidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("MIN_HUMIDITY");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("SCIENTIFIC_NAME");

                    b.Property<int>("WateringMl")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("WATERING_ML");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .IsUnique();

                    b.ToTable("TB_CAD_SPECIES", (string)null);
                });

            modelBuilder.Entity("AgroMonitor.Domain.Entities.Slot", b =>
                {
                    b.HasOne("AgroMonitor.Domain.Entities.Species", "Species")
                        .WithMany("Slots")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("AgroMonitor.Domain.Entities.Species", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
