namespace AgroMonitor.Domain.Common;

/// <summary>
/// Base de todas as entidades de domínio.
/// O Id é numérico (long) porque o schema Oracle compartilhado usa
/// NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY — o banco gera o valor,
/// e a API Java já lê esses Ids como número. Por isso não usamos Guid aqui.
/// </summary>
public abstract class BaseEntity
{
    public long Id { get; protected set; }

    public DateTime CreatedAt { get; protected set; } = DateTime.UtcNow;
}
